theme: jekyll-theme-minimal
title: Chris Harvey's Code homepage
description: I am a Graduate from Newcastle University with a First Class Masters degree in Computer Science. This site gives an overview and portal into the software projects I have delivered as part of this degree over the last 4 years.
